# Стадия 1: Сборка
FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /build/wms-service ./cmd/main.go

# Стадия 2: Финальный образ
FROM alpine:latest

WORKDIR /app

COPY --from=builder /build/wms-service .

CMD ["./wms-service"]