#!/usr/bin/env bash
# deploy-geo.sh — deploy BatchMappingWMS to the GEO subnet chain via node-home (host loopback :9750).
#
# Host-side mirror of deploy/contracts/deploy.sh: SAME ewoq deployer, SAME idempotency + sanity check,
# but it targets the geo subnet chain (networkID 1338, chainID 99999) through the local node-home RPC
# gateway and records the deployed address in deploy/geo/genesis/contract.env (gitignored).
#
# Isolation (C-5): reuses ledger-adapter/contracts ONLY as read-only Solidity source (forge artifacts
# go to /tmp). Does NOT touch deploy/contracts, the shared_state volume, or any running validator.
#
# Prereqs: node-home up (docker compose -f deploy/geo/docker-compose.geo.yaml up -d), foundry local.
#   deploy/geo/contracts/deploy-geo.sh
set -euo pipefail
cd "$(dirname "$0")"                                   # deploy/geo/contracts
GEO_GENESIS="../genesis"
# shellcheck disable=SC1091
. "$GEO_GENESIS/chain-ids.env"                         # BLOCKCHAIN_ID
: "${BLOCKCHAIN_ID:?set BLOCKCHAIN_ID (deploy/geo/genesis/chain-ids.env)}"

EWOQ_KEY='0x56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027'  # canonical prefunded key
RPC_URL="${GEO_DEPLOY_RPC:-http://localhost:9750/ext/bc/${BLOCKCHAIN_ID}/rpc}"  # node-home, host loopback
ENV_OUT="$GEO_GENESIS/contract.env"
CONTRACTS_DIR="../../../ledger-adapter/contracts"     # repo-root/ledger-adapter/contracts (read-only use)

echo "==> geo RPC: $RPC_URL"
CHAIN_ID=$(cast chain-id --rpc-url "$RPC_URL")
[ "$CHAIN_ID" = "99999" ] || { echo "FATAL: expected chainID 99999, got '$CHAIN_ID' — wrong RPC/node?"; exit 1; }
echo "==> geo chain live, chainID=$CHAIN_ID"

# Idempotency: skip redeploy if contract.env already points to a live contract on the geo chain.
# A transient RPC error on `cast code` must NOT trigger a blind redeploy (would orphan the old
# contract under the same ewoq nonce) — fail loudly instead.
if [ -f "$ENV_OUT" ]; then
  # shellcheck disable=SC1090
  . "$ENV_OUT"
  if [ -n "${GEO_CONTRACT_ADDR:-}" ]; then
    if ! CODE=$(cast code "$GEO_CONTRACT_ADDR" --rpc-url "$RPC_URL" 2>&1); then
      echo "FATAL: cast code for $GEO_CONTRACT_ADDR failed: $CODE"
      echo "       refusing to redeploy blindly — fix RPC or rm $ENV_OUT to force redeploy"; exit 1
    fi
    if [ "${#CODE}" -gt 4 ]; then
      echo "==> already deployed at $GEO_CONTRACT_ADDR — skipping redeploy"; exit 0
    fi
    echo "==> stale contract.env ($GEO_CONTRACT_ADDR has no code), redeploying"
  fi
fi

cd "$CONTRACTS_DIR"
# Keep forge artifacts out of the source tree (don't churn ledger-adapter/contracts).
export FOUNDRY_OUT=/tmp/forge-geo-out FOUNDRY_CACHE_PATH=/tmp/forge-geo-cache
mkdir -p "$FOUNDRY_OUT" "$FOUNDRY_CACHE_PATH"

echo "==> deploying BatchMappingWMS to geo chain"
OUT=$(forge create BatchMappingWMS \
  --rpc-url "$RPC_URL" \
  --private-key "$EWOQ_KEY" \
  --broadcast \
  --json)
ADDR=$(echo "$OUT" | jq -r '.deployedTo')
TX=$(echo   "$OUT" | jq -r '.transactionHash')
[ -n "$ADDR" ] && [ "$ADDR" != "null" ] || { echo "FATAL: no deployedTo in forge output: $OUT"; exit 1; }

echo "==> sanity: itemStatus(0) must be 0 (None)"
STATUS=$(cast call "$ADDR" "itemStatus(uint256)(uint8)" 0 --rpc-url "$RPC_URL")
[ "$STATUS" = "0" ] || { echo "FAIL: itemStatus(0) = $STATUS"; exit 1; }

cd - >/dev/null
cat > "$ENV_OUT" <<EOF
# generated by deploy-geo.sh — BatchMappingWMS on the geo subnet chain (gitignored)
GEO_CONTRACT_ADDR=$ADDR
GEO_DEPLOY_TX=$TX
EOF
echo "==> deployed BatchMappingWMS at $ADDR"
echo "    tx $TX"
echo "    recorded -> $ENV_OUT"
echo "OK"
